{
 "title": "RabbitMQ-PerfTest",
 "tags": [ "rabbitmq-perf-test" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "PerfTest Instance",
    "query": {
     "query": "label_values(perftest_published, instance)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": {
     "query": "label_values(perftest_latency_seconds, quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LATENCY",
   "type": "row",
   "description": "RabbitMQ message latency & throughput across all PerfTest instances",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "End-to-end message latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "perftest_latency_seconds{quantile=\"$percentile\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end message latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "perftest_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end message latency distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "perftest_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"} > 0"
    }
   ]
  },
  {
   "title": "End-to-end message latency distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "perftest_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Publish confirm latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "perftest_confirm_latency_seconds{quantile=\"$percentile\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Publish confirm latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "perftest_confirm_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Publish confirm latency distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "perftest_confirm_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"} > 0"
    }
   ]
  },
  {
   "title": "Publish confirm latency distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "perftest_confirm_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "THROUGHPUT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Messages published / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "perftest_published", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages published / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "perftest_published{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages consumed / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "perftest_consumed{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages consumed / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "perftest_consumed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages confirmed / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "perftest_confirmed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages confirmed / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "perftest_confirmed{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages rejected / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "perftest_nacked{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages rejected / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "perftest_nacked", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages returned / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "perftest_returned", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages returned / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "perftest_returned{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}